# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ly2ss_pQ8OsRn_COGKHjIJ5ebS6GrstM
"""

!pip install translate

from translate import Translator

# @markdown ### 🤖 Escribe aquí tu texto:
texto_a_traducir = "Hola mi nombre es Daniela" # @param {type:"string"}

try:
    # Configuramos para traducir de español (es) a inglés (en)
    traductor = Translator(from_lang="es", to_lang="en")
    resultado = traductor.translate(texto_a_traducir)

    # Aquí abajo es donde verás impreso tu resultado final:
    print("=" * 40)
    print(f"Texto Original: {texto_a_traducir}")
    print(f"Traducción:     {resultado}")
    print("=" * 40)
except Exception as e:
    print("Hubo un error del sistema. Inténtalo una vez más.")